server:
  addr: "0.0.0.0:8080"

database:
  type: "sqlite"
  sqlite_path: "data/punching-fist.db"
  max_connections: 5

kube:
  namespace: "default"
  service_account: "punching-fist"

openhands:
  api_url: "http://localhost:8080"
  api_key: "" 