{{- if .Values.security.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-crd-access
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  # CRD access
  - apiGroups: ["punchingfist.io"]
    resources: ["sources", "workflows", "sinks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["punchingfist.io"]
    resources: ["sources/status", "workflows/status", "sinks/status"]
    verbs: ["get", "patch", "update"]
{{- end }} 