{{- if or .Values.agent.anthropicApiKey .Values.agent.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "punching-fist.fullname" . }}-agent
  labels:
    {{- include "punching-fist.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.agent.anthropicApiKey }}
  anthropic-api-key: {{ .Values.agent.anthropicApiKey | b64enc | quote }}
{{- end }}
{{- if .Values.agent.openaiApiKey }}
  openai-api-key: {{ .Values.agent.openaiApiKey | b64enc | quote }}
{{- end }}
{{- end }} 