{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "punching-fist.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "punching-fist.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "punching-fist.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
{{- end }} 