# Local development values for punching-fist operator
# Use this file for local Kubernetes deployment with: helm install --values values-local.yaml

# Global settings for local development
global:
  image:
    repository: ttl.sh/punching-fist-operator
    tag: "2h"
    pullPolicy: Always

# Operator configuration
operator:
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Server configuration
server:
  port: 8080
  host: "0.0.0.0"

# Persistence configuration for SQLite database
persistence:
  enabled: true
  size: 500Mi
  storageClass: ""  # Use default storage class for local development
  accessMode: ReadWriteOnce

# Prometheus configuration
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true  # Enable ServiceMonitor since we have prometheus-operator
    interval: 15s

# Security configuration
security:
  serviceAccount:
    create: true
    name: punching-fist
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["pods", "services", "configmaps", "secrets"]
        verbs: ["get", "list", "watch", "create", "update", "delete"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["get", "list", "watch", "create", "update", "delete"]
      - apiGroups: ["apps"]
        resources: ["deployments", "replicasets"]
        verbs: ["get", "list", "watch"]

# Pod security context
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

# Container security context  
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # Set to false to allow writing to mounted volumes
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# Test resources configuration - enabled for local development
testResources:
  enabled: true  # Deploy test workloads automatically
  namespace: test-workloads

# Prometheus Stack configuration - enabled for local development
prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      # Smaller resources for local development
      resources:
        requests:
          memory: 200Mi
          cpu: 50m
        limits:
          memory: 400Mi
          cpu: 200m
      # Smaller storage for local
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 500Mi
      # Shorter retention for local
      retention: 1d
      # Select all service monitors
      serviceMonitorSelector: {}
      # NodePort for easy access from host
      service:
        type: NodePort
        nodePort: 30090
  # Minimal components for local testing
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false

# Agent configuration
agent:
  # Default to mock provider for local testing without API keys
  provider: "mock"  
  anthropicApiKey: ""  # Set via --set agent.anthropicApiKey=your_key or use deploy-local-with-key command
  openaiApiKey: ""     # Set via --set agent.openaiApiKey=your_key

# Use NodePort for easier local access
service:
  type: NodePort
  nodePort: 30080 