apiVersion: punchingfist.io/v1alpha1
kind: Source
metadata:
  name: alertmanager-critical
  namespace: punchingfist-system
spec:
  type: webhook
  config:
    path: "/alerts/critical"
    filters:
      severity:
        - critical
        - warning
      alertname:
        - HighCPUUsage
        - PodCrashLooping
        - MemoryPressure
    authentication:
      type: bearer
      secretRef: alertmanager-webhook-token
  triggerWorkflow: alert-triage-workflow
  context:
    runbookRepo: "https://github.com/company/runbooks"
    slackChannel: "#ops-alerts" 